wiremock:
  endpoint: http://localhost:8081
server:
  error:
      include-message: always
spring:
  datasource:
    url: jdbc:h2:file:./data/folder
    driver-class-name: org.h2.Driver
    username: user
    password: "pass"
  h2:
    console:
      enabled: true
      path: /application-database
      settings:
        trace: false
        web-allow-others: false
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform:  org.hibernate.dialect.H2Dialect